FROM quay.io/openshift/origin-machine-config-operator:4.8 as mcd
FROM quay.io/openshift/origin-artifacts:4.8 as artifacts

FROM quay.io/coreos-assembler/coreos-assembler:latest AS build
WORKDIR /src
COPY . .
COPY --from=mcd /usr/bin/machine-config-daemon /overrides/rootfs/usr/libexec/machine-config-daemon
COPY --from=artifacts /srv/repo/*.rpm /overrides/rpms/
LABEL foo bar
ENTRYPOINT ["/src/entrypoint.sh"]
